-- Migration 0001: identity foundation (users, devices, sessions, invites, audit).
--
-- Conventions
--   * IDs are opaque random strings generated by the server.
--   * Timestamps are INTEGER Unix epoch milliseconds (UTC).
--   * Secrets (invite codes, refresh tokens, recovery keys) are high-entropy
--     random values and are stored ONLY as SHA-256 hashes.
--   * No message content is ever stored in D1 audit/log tables.
--
-- Until the first remote deploy this file may still be amended; afterwards,
-- schema changes must go in new numbered migrations.

CREATE TABLE users (
  id                TEXT PRIMARY KEY,
  username          TEXT NOT NULL UNIQUE COLLATE NOCASE,
  display_name      TEXT NOT NULL,
  avatar_key        TEXT,                                  -- R2 object key
  role              TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'admin')),
  status            TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  invited_by        TEXT REFERENCES users (id) ON DELETE SET NULL,
  recovery_key_hash TEXT,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL
);

-- A device is the unit of authentication (and, from Phase 8, of encryption).
-- Each device holds a private signing key in secure hardware-backed storage;
-- the server stores only the public key.
CREATE TABLE devices (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name                TEXT NOT NULL,
  platform            TEXT NOT NULL CHECK (platform IN ('ios', 'android')),
  signing_public_key  TEXT NOT NULL UNIQUE,                -- base64url Ed25519
  created_at          INTEGER NOT NULL,
  last_seen_at        INTEGER,
  revoked_at          INTEGER
);
CREATE INDEX devices_user_id ON devices (user_id);

-- One row per refresh-token family. The token rotates on every refresh;
-- presenting a previous token (reuse) revokes the whole session.
CREATE TABLE sessions (
  id                          TEXT PRIMARY KEY,
  device_id                   TEXT NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
  refresh_token_hash          TEXT NOT NULL UNIQUE,
  previous_refresh_token_hash TEXT,
  created_at                  INTEGER NOT NULL,
  rotated_at                  INTEGER,
  expires_at                  INTEGER NOT NULL,
  revoked_at                  INTEGER
);
CREATE INDEX sessions_device_id ON sessions (device_id);
CREATE INDEX sessions_previous_refresh_token_hash ON sessions (previous_refresh_token_hash);

CREATE TABLE invites (
  id          TEXT PRIMARY KEY,
  code_hash   TEXT NOT NULL UNIQUE,
  created_by  TEXT REFERENCES users (id) ON DELETE SET NULL, -- NULL = bootstrap invite
  max_uses    INTEGER NOT NULL DEFAULT 1 CHECK (max_uses > 0),
  use_count   INTEGER NOT NULL DEFAULT 0 CHECK (use_count >= 0),
  expires_at  INTEGER NOT NULL,
  revoked_at  INTEGER,
  created_at  INTEGER NOT NULL
);
CREATE INDEX invites_created_by ON invites (created_by);

-- Security-relevant events only (logins, device changes, invite use).
-- Never store message contents, tokens, keys or raw IP addresses here.
CREATE TABLE audit_events (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  event       TEXT NOT NULL,
  user_id     TEXT REFERENCES users (id) ON DELETE SET NULL,
  device_id   TEXT REFERENCES devices (id) ON DELETE SET NULL,
  metadata    TEXT,                                        -- small JSON object
  created_at  INTEGER NOT NULL
);
CREATE INDEX audit_events_user_id_created_at ON audit_events (user_id, created_at);
